import type { Metadata } from "next";
import { Lato } from "next/font/google";
import Navbar from './components/layout/Navbar';
import { ClientSessionProvider } from './components/layout/sessionProvider';
import { auth } from './api/auth';
import "./globals.css";


const lato = Lato( {
  weight: [  '300', '400', '700' ],
  subsets: [ 'latin' ],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}> )
{
  
  const session = await auth();

  return (
    <ClientSessionProvider session={session}>
      <html lang="en">
        <body
          className={`${lato.className} antialiased text-slate-500`}
        >
          <div className='relative h-screen overflow-hidden'>
            <Navbar />
            <div className='w-full h-[calc(100vh-112px)] overflow-auto'>
              {children}
            </div>
          </div>
        </body>
      </html>
    </ClientSessionProvider>
  );
}
