import type { Metadata } from "next";
import { Lato } from "next/font/google";
import Navbar from './components/layout/Navbar';
import "./globals.css";


const lato = Lato( {
  weight: [ '100', '300', '400', '700', '900' ],
  subsets: [ 'latin' ],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lato.className} antialiased text-slate-500`}
      >
        <main className='relative'>
          <Navbar />
          <div className='absolute top-28 inset-x-0 h-[calc(100vh-112px)]'>
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
